### ISSUE TITLE
ScrabbleScore tests for Swift

### ISSUE THREAD

**Issue by stevencurtis** [exercism/swift#268]
A minor issue. One of the tests for Scrabble score for swift is called testConvenientScoring() - this is potentially confusing as it brings to mind convenience initializers, yet is nothing to do with that.

**Comment by masters3d** [comment]
Sounds good. I wouldn't be opposed to a PR changing that name. :)

**Comment by morrme** [comment]
@masters3d what would be an appropriate name?

**Comment by masters3d** [comment]
I'll let you decide.

**Comment by morrme** [comment]
@masters3d I am not the issue author so @stevencurtis back to you. If there's a name that works better for you , I'm happy to implement it.

**Comment by masters3d** [comment]
Naming is one of the hardest problems in computer science. :)

**Comment by morrme** [comment]
@masters3d it really, really is! i know that whatever name i would pick would then be confusing/conflicting with something else so i didn't even try.

**Comment by masters3d** [comment]
It's all good. You can always make the name longer to be specific. That's what the iOS API tends to do.
