### ISSUE TITLE
How does the Swift track check code complexity?

### ISSUE THREAD

**Issue by wolf99** [exercism/swift#311]
I got side-tracked to a Swift PR from an issue on the main Exercism repo and noticed that this track has reports on code complexity analysis. How is this done? Could it be applied to other language tracks?
Thanks

**Comment by masters3d** [comment]
https://github.com/realm/SwiftLint

Another options for other languages.

**Comment by masters3d** [comment]
forgot to add this: https://github.com/exercism/java/issues/1006#issuecomment-347698464
