### ISSUE TITLE
Pangram in Swift Track Includes Test for Non-ASCII Characters Despite Readme

### ISSUE THREAD

**Issue by p0st0culus** [exercism/swift#314]
The Pangram problem in the Swift track includes a test case for non-ASCII characters in the last test, even though the Readme specifically says that input will not contain non-ASCII characters.

Looking at the Canonical Problem Specifications, this test does _not_ appear in the JSON file.

This isn't too hard to code for, at least in Swift, but a bit contrary to expectations laid out in the Readme.

Recommend either updating the Swift Pangram test suite to exclude the non-ASCII test (it's the last test), or update the Readme.  The latter would also require updating the Canonical Problem Specifications and any other language tracks that matches it currently.

**Comment by masters3d** [comment]
Good point. We should update our version of the readme. Would you like to summit a PR?

We are not longer trying to keep all the different versions of the problems to have the same specs. Swift doesn’t use the Canonical Json so we do not need to keep these in sync. 

There is probably more info on this but I can’t find it right now.

**Comment by p0st0culus** [comment]
Oh, based on replies to the previous report I submitted, I thought everything was converging on using the Canonical JSON.

Hmm…

What do I need to submit?  I’m a little confused on what reports should be submitted where, actually.

**Comment by masters3d** [comment]
The readme should reflect what’s is on our actual test cases. You can submit a PR against our readme for the exercise

**Comment by masters3d** [comment]
Reopen if you still feel it has not been addressed.
