### ISSUE TITLE
Problem with Xcode wrong error

### ISSUE THREAD

**Issue by budhead** [exercism/swift#321]
Xcode Version 9.2 (9C40b)

This is not stopping the work, but it's confusing so probably it should be mentioned in the setup guide.

When I open the project the project compiles and probably because the project file is empty it is not creating the package. After creating function, class or whatever everything is ok, but Test environment already cached this and trows strange errors that are ignored even by the compiler, they are just shown. Even after the task is finished and all tests pass, the errors are still there. 
This can not be fixed by clean or clean build folder.

The only solution I found is comment out "@testable import Leap". Then build. An error occurs, but after you uncomment the line and build again, everything is fine. No errors occur.
<img width="1401" alt="screen shot 2018-01-19 at 16 05 57" src="https://user-images.githubusercontent.com/2962473/35154907-ab8379b4-fd34-11e7-977b-456254b01dc2.png">
<img width="1402" alt="screen shot 2018-01-19 at 16 17 05" src="https://user-images.githubusercontent.com/2962473/35154908-aba33010-fd34-11e7-8c7d-68715e911fd3.png">
<img width="1401" alt="screen shot 2018-01-19 at 16 17 42" src="https://user-images.githubusercontent.com/2962473/35154909-abc8193e-fd34-11e7-8412-9d1ef94d8c2a.png">
<img width="1401" alt="screen shot 2018-01-19 at 16 18 00" src="https://user-images.githubusercontent.com/2962473/35154910-abe8f712-fd34-11e7-9939-b92a96483fc7.png">

**Comment by masters3d** [comment]
This seems to be an Xcode bug.
Do you mind filing a radar you file a radar?

**Comment by masters3d** [comment]
Have you tried the new xcode?

**Comment by masters3d** [comment]
Reopen if you are still having issues.
