### ISSUE TITLE
cannot load underlying module for 'XCTest'

### ISSUE THREAD

**Issue by Xwil** [exercism/swift#327]
when running "swift test" from command-line:
Compile Swift Module 'HelloWorldTests' (1 sources)
/Users/xiangwei/开发/Exercism/swift/hello-world/Tests/HelloWorldTests/HelloWorldTests.swift:1:8: error: cannot load underlying module for 'XCTest'
import XCTest
       ^
error: terminated(1): /Library/Developer/CommandLineTools/usr/bin/swift-build-tool -f '/Users/xiangwei/开发/Exercism/swift/hello-world/.build/debug.yaml' test

Test succeeded in XCode.
I manully add XCTest.framework to HelloWorldTests target, still wrong.

**Comment by masters3d** [comment]
what version of xcode?

**Comment by masters3d** [comment]
running tests on xcode 9, 9. and 9.2
https://github.com/exercism/swift/pull/328

**Comment by masters3d** [comment]
Those tests are passing. Let’s me know.

**Comment by masters3d** [comment]
Reopen if you are still having issues.
