### ISSUE TITLE
gigasecond: support ability to use ISO8601DateFormatter?

### ISSUE THREAD

**Issue by jvarness** [exercism/swift#335]
I was doing the gigasecond problem, and I noticed that I couldn't use the [ISO8601DateFormatter](https://developer.apple.com/documentation/foundation/iso8601dateformatter).

I think the reason might have been that the date/times used in the test cases need `Z` appended to them.

I could probably use regular [DateFormatter](https://developer.apple.com/documentation/foundation/dateformatter) class too, but the ISO8601DateFormatter would make this much easier to solve.

I also looked at the [example solution](https://github.com/exercism/swift/blob/master/exercises/gigasecond/Sources/GigasecondExample.swift) for this problem, but I thought it looked pretty involved. Is the idea that participants of exercism try to solve the problem without using standard Swift libraries?

References:
https://en.wikipedia.org/wiki/ISO_8601

**Comment by masters3d** [comment]
The tests are created so people do not have to use the standard library if they do not want to. 
To me the main learning for the problem is how to deal with timezones. 

Z is not included because it should be zero. 

https://stackoverflow.com/a/8405125/3705470

This is how to can get the timezone in NSDateFormater in swift 2

```
dateFormatter.timeZone = NSTimeZone(forSecondsFromGMT: 0)
```

**Comment by masters3d** [comment]
let me know if you have any other questions about the implementation. Pull Requests are always welcome.

**Comment by jvarness** [comment]
Yea I was trying to create a date formatter that didn't include zone but I guess the ISO8601DateFormatter might not allow for ambiguous zones. I bet I could use the DateFormatter class and it would work ok.

I'll try some alternatives and let you know what I come up with.
