### ISSUE TITLE
Rna Transcript Tests that test throwing functions with error messages are confusing

### ISSUE THREAD

**Issue by Zialus** [exercism/swift#356]
When solving the exercise `Rna Transcript` I found the test suite to be a bit strange.

Specifically, I found confusing the message parameter used in the [XCTAssertThrowsError function](https://github.com/exercism/swift/blob/master/exercises/rna-transcription/Tests/RnaTranscriptionTests/RnaTranscriptionTests.swift#L25-L50)

`XCTAssertThrowsError(try Nucleotide("XXX").complementOfDNA(), "This didn't work")`

`_ expression: @autoclosure () throws -> T, _ message: @autoclosure () -> String = default`

[Here's the documentation for XCTAssertThrowsError](https://developer.apple.com/documentation/xctest/1500795-xctassertthrowserror)

I asked the mentor that reviewed the exercise about it, but he didn't comment on it.

Wouldn't it be better to change the tests to something like what is done in the [Grains](https://github.com/exercism/swift/blob/master/exercises/grains/Tests/GrainsTests/GrainsTests.swift#L6-L34) exercise?

**Comment by masters3d** [comment]
Good point. Pull request welcome. Thanks!

**Comment by Zialus** [comment]
Sure, give me some minutes.
