### ISSUE TITLE
Discrepancy in config.json exercise name and file system name

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/swift#444]
The config.json file contains an exercise named `bomb-diffuser`, but the file system contains an exercise named `bomb-defuser`. One of these should be changed to have them aligned :)

**Comment by iHiD** [comment]
@ErikSchierboom Can you choose a "correct" one and merge pls?

**Comment by ErikSchierboom** [comment]
@iHiD Done: https://github.com/exercism/swift/pull/452
