### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/swift#476]
This repository's `main` branch currently does not pass all CI checks.
This makes detecting issues in PRs harder and might result in a broken track, and so is an important thing to fix.

The following CI workflows are currently failing:

https://github.com/exercism/swift/runs/3370849643

## Tracking

https://github.com/exercism/v3-launch/issues/55

**Comment by sanderploegsma** [comment]
Should be fixed after merging #484 and #487 I think

**Comment by kerolloz** [comment]
@ErikSchierboom 
Tests pass here 
![image](https://user-images.githubusercontent.com/36763164/196004963-1edab6da-6d9b-4688-9ead-4670226494da.png)
