### ISSUE TITLE
Cal's Custom Sign Shop Exercise unable to pass my code while all test case I have checked locally.. 

### ISSUE THREAD

**Issue by zzy98y** [exercism/swift#535]
```
let birthday:String = "Birthday" 
let valentine:String = "Valentine's Day"
let anniversary:String = "Anniversary"
let space: Character = " "
let exclamation: Character = "!"
```

```
func buildSign(for occasion: String, name: String) -> String {

  return "Happy \(occasion) \(name)" + String(exclamation)
} 

func graduationFor(name: String, year: Int) -> String {

  return "Congratuations \(name)" + String(exclamation) + " \nClass of \(year)"
}

func costOf(sign: String) -> Int {
  return sign.count * 2 + 20
}

```

Above is the code I submitted for the **Cal's Custom Sign Shop exercise in Swift**. I don't know why it does not let me pass. I have manually tested all the test case that's in the source code locally, it's exactly the same. 

So I don't know what is the issue here, please either let me know what I did wrong in my code or fix this exercise. 

Thank you very much! 

Update: 

There is this space in this line of code: `return "Congratuations \(name)" + String(exclamation) + " \nClass of \(year)"` 
Specifically the last quotation and `\n`, that's the reason caused the tests to fail.

**Comment by ErikSchierboom** [comment]
I don't know if this fixes all your issues, but there is a typo in `Congratuations`, which should be `Congratulations`.

**Comment by zzy98y** [comment]
> I don't know if this fixes all your issues, but there is a typo in `Congratuations`, which should be `Congratulations`.

I fix the typo, and issue still persist after I click `submit`.

**Comment by ErikSchierboom** [comment]
I would then suggest to ask for help in Exercism's gitter channel: https://gitter.im/exercism

**Comment by iHiD** [comment]
Comparing your code to https://github.com/exercism/swift/blob/main/exercises/concept/custom-signs/.meta/Sources/CustomSigns/CustomSignsExemplar.swift , it looks like you have an space in graduationFor (`" \n`).

Based on what Erik said (the typo) the code couldn't have been passing locally beforehand. Do you have a screenshot of what error you get when you run this in the editor pls?

**Comment by iHiD** [comment]
@ErikSchierboom Could you take a look at this pls to see why the Test Runner isn't giving output?

**Comment by zzy98y** [comment]
> @ErikSchierboom Could you take a look at this pls to see why the Test Runner isn't giving output?

I want to follow up as well. I have been practicing with other languages as well, Swift is the only one that does not tell me what my errors are, just give me a plank **TESTS FAILED**.  Please make it like other programming language so it actually show me which test case I failed. 

Thank you!

**Comment by ErikSchierboom** [comment]
It looks like this was caused by a missing `version` key: https://github.com/exercism/swift-test-runner/pull/31/files
