### ISSUE TITLE
Some concept exercises have 2 source and test directories

### ISSUE THREAD

**Issue by dlwalter** [exercism/swift#541]
A few concept exercises (for example, Santa Swifty Helper, and Magician in Training) have a Source directory as well as an org-sources directory.  Same goes for Tests and org-tests directory. I'm guessing this is leftover from an update?

This is confusing for new users.

**Comment by ErikSchierboom** [comment]
@dlwalter Would you be willing to submit a PR to fix this?

**Comment by dlwalter** [comment]
@ErikSchierboom done.

https://github.com/exercism/swift/pull/542

**Comment by ErikSchierboom** [comment]
Closed by #542
