### ISSUE TITLE
Windowing System: cannot create a new window

### ISSUE THREAD

**Issue by CarbonHeartDev** [exercism/swift#612]
If I create and populate the mainWindow instance of Window I get the "expressions are not allowed at the top level" compile error because it seems that Swift doesn't accept expressions outside function and methods unless it's in the main file but if I remove the statements needed to create and configure the new window I get the "cannot find 'mainWindow' in scope" compile error.

I'm stuck and I'm not sure if there's something I don't understood or its a bug in the exercise.

**Comment by mpbarlow** [comment]
@CarbonHeartDev You can get around this by using an immediately-invoked closure, like so:

```swift
var mainWindow = {
    var window = Window()
    
    window.update(title: "Main Window")
    window.update(text: "This is the main window")

    window.resize(to: Size(width: 400, height: 300))
    window.move(to: Position(x: 100, y: 100))
    
    return window
}()
```

The test cases themselves use this approach, however I totally agree that this is a something that should be explained in the instructions (or avoided entirely by reworking the tests).

**Comment by CarbonHeartDev** [comment]
Thanks @mpbarlow and sorry for the late answer. Now I can properly finish the Swift course 😁
