### ISSUE TITLE
Saddle points formatting problem

### ISSUE THREAD

**Issue by reisdev** [exercism/swift#717]
The table containing the grid from the [Saddle Points exercise](https://exercism.org/tracks/swift/exercises/saddle-points) has a formatting problem.

The current state looks like this:

<img width="664" alt="image" src="https://github.com/exercism/swift/assets/23380987/b04bba66-89ad-4fed-ae2e-d198245b0dc5">

It's missing the three backticks wrapping the table, so it can be properly formatted. It should look like this(from [Python exercise](https://exercism.org/tracks/python/exercises/saddle-points)):

<img width="664" alt="image" src="https://github.com/exercism/swift/assets/23380987/fa0c526b-8d44-4046-9245-635cc8a58e9f">

**Comment by meatball133** [comment]
H! Thanks for reporting, I will fix it hopefully tomorrow.
