### ISSUE TITLE
Errors in conditionals/vehicle-purchase?

### ISSUE THREAD

**Issue by rhoot** [exercism/swift#810]
Going over the conditionals exercise (vehicle-purchase), it has these two tests:

https://github.com/exercism/swift/blob/4dea7e2b6dc717d04c1e68cb1221dd33f6416df5/exercises/concept/vehicle-purchase/Tests/VehiclePurchaseTests/VehiclePurchaseTests.swift#L9-L11

https://github.com/exercism/swift/blob/4dea7e2b6dc717d04c1e68cb1221dd33f6416df5/exercises/concept/vehicle-purchase/Tests/VehiclePurchaseTests/VehiclePurchaseTests.swift#L23-L25

But the instructions say:

> The function should return the following message based on the following conditions:
> 
> - If the price of the vehicle is less than or equal to the monthly budget, return the message "Yes! I'm getting a &lt;vehicle>".
> - If the price of the vehicle is 10% above your monthly budget, return the message "I'll have to be frugal if I want a &lt;vehicle>".
> - If the price of the vehicle is more than 10% above your monthly budget, return the message "Darn! No &lt;vehicle> for me".

516.32 is more than 10% above the monthly budget (100), so it shouldn't say yes. Likewise, 12,500 is quite a bit more than 10% over the monthly budget of 200, so it shouldn't say you have to be frugal.

**Comment by meatball133** [comment]
It is not an error per say, the instructions say:

> The auto dealers in your town are all running a five year, 0% interest promotion that you would like to take advantage of. But you are not sure if you can afford the monthly payments on the car you want.

So what you are suppose to do is take the price divide by the five years, and then by 12 months. So in total 60 months.

12,500 / 60 -> 208, and that is 10% above the rate.

I will update the instructions to highlight this manner, in a future update. Not sure when.

**Comment by rhoot** [comment]
> It is not an error per say, the instructions say: [...]

Ah right, that had slipped my mind by the time I got to the instructions. Would definitely be clearer to refer to the payment as the "price of the monthly payment" instead of the "price of the vehicle".
